In [4]:
import pandas as pd


df = pd.read_parquet("master_dataset.parquet")
display(df)

print(df.columns)

,date,ticker,open,high,low,close,volume,source_file,source_month,adj_close,...,Sektor,SubSektor,market_cap,listed_shares,usdidr,brent_usd,coal_usd,bi_rate_pct,daily_return,intraday_move
0,2015-01-02,AALI,16715.333882,17196.845842,16680.940171,16904.500000,1385945.0,None,None,16904.500000,...,Barang Konsumen Primer,Makanan & Minuman,NaN,NaN,12390.0,48.933182,64.716327,4.75,NaN,0.011317
1,2015-01-02,ABBA,48.466820,50.055897,48.466820,49.261356,117049.0,None,None,49.261356,...,Barang Konsumen Non-Primer,Media & Hiburan,NaN,NaN,12390.0,48.933182,64.716327,4.75,NaN,0.016393
2,2015-01-02,ABDA,5533.175293,5533.175293,5533.175293,5533.175293,5000.0,None,None,5533.175293,...,Keuangan,Asuransi,NaN,NaN,12390.0,48.933182,64.716327,4.75,NaN,0.000000
3,2015-01-02,ABMM,2110.177002,2110.177002,2110.177002,2110.177002,0.0,None,None,2110.177002,...,Energi,"Minyak, Gas & Batu Bara",NaN,NaN,12390.0,48.933182,64.716327,4.75,NaN,0.000000
4,2015-01-02,ACES,576.700535,580.373786,569.354031,573.027283,15328600.0,None,None,573.027283,...,Barang Konsumen Non-Primer,Perdagangan Ritel,NaN,NaN,12390.0,48.933182,64.716327,4.75,NaN,-0.006369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1906999,2026-03-06,ZATA,133.000000,133.000000,133.000000,133.000000,1219300.0,all_2026_ohlcv.csv,ohlcv,133.000000,...,Barang Konsumen Non-Primer,Perdagangan Ritel,1.129968e+12,8.496000e+09,16913.1,64.594091,115.815000,4.75,-0.095238,0.000000
1907000,2026-03-06,ZBRA,50.000000,0.000000,0.000000,50.000000,0.0,all_2026_ohlcv.csv,ohlcv,50.000000,...,Perindustrian,Perusahaan Holding Multi Sektor,1.255353e+11,2.510706e+09,16913.1,64.594091,115.815000,4.75,0.000000,0.000000
1907001,2026-03-06,ZINC,35.000000,35.000000,34.000000,35.000000,8051600.0,all_2026_ohlcv.csv,ohlcv,35.000000,...,Barang Baku,Barang Baku,8.837500e+11,2.525000e+10,16913.1,64.594091,115.815000,4.75,0.029412,0.000000
1907002,2026-03-06,ZONE,466.000000,476.000000,440.000000,466.000000,5900.0,all_2026_ohlcv.csv,ohlcv,466.000000,...,Barang Konsumen Non-Primer,Perdagangan Ritel,4.054999e+11,8.701715e+08,16913.1,64.594091,115.815000,4.75,-0.021008,0.000000
1907003,2026-03-06,ZYRX,149.000000,149.000000,146.000000,148.000000,200800.0,all_2026_ohlcv.csv,ohlcv,148.000000,...,Teknologi,Perangkat Keras & Peralatan Teknologi,1.973335e+11,1.333335e+09,16913.1,64.594091,115.815000,4.75,-0.006711,-0.006711

Index(['date', 'ticker', 'open', 'high', 'low', 'close', 'volume',
       'source_file', 'source_month', 'adj_close', 'Industri', 'SubIndustri',
       'Sektor', 'SubSektor', 'market_cap', 'listed_shares', 'usdidr',
       'brent_usd', 'coal_usd', 'bi_rate_pct', 'daily_return',
       'intraday_move'],
      dtype='object')

In [2]:
listed_shares = pd.read_csv("data/listed_shares/listed_shares.csv")
listed_shares

,date,ticker,close,listed_shares,market_cap,source_file,source_month
0,2020-01-02,AALI,14025,1924688333,26993753870325,all_2020_market_cap.csv,market_cap
1,2020-01-02,ABBA,105,2755125000,289288125000,all_2020_market_cap.csv,market_cap
2,2020-01-02,ABDA,6925,620806680,4299086259000,all_2020_market_cap.csv,market_cap
3,2020-01-02,ABMM,1530,2753165000,4212342450000,all_2020_market_cap.csv,market_cap
4,2020-01-02,ACES,1510,17150000000,25896500000000,all_2020_market_cap.csv,market_cap
...,...,...,...,...,...,...,...
1280524,2026-03-06,ZATA,133,8496000000,1129968000000,all_2026_market_cap.csv,market_cap
1280525,2026-03-06,ZBRA,50,2510706263,125535313150,all_2026_market_cap.csv,market_cap
1280526,2026-03-06,ZINC,35,25250000000,883750000000,all_2026_market_cap.csv,market_cap
1280527,2026-03-06,ZONE,466,870171478,405499908748,all_2026_market_cap.csv,market_cap
1280528,2026-03-06,ZYRX,148,1333334556,197333514288,all_2026_market_cap.csv,market_cap

In [2]:
ohlcv = pd.read_csv("data/ohlcv/ohlcv.csv")
ohlcv

/var/folders/pt/n4kz04ns6wn8sv6msgx6mqb80000gn/T/ipykernel_23059/2565488563.py:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  ohlcv = pd.read_csv("data/ohlcv/ohlcv.csv")

,date,ticker,open,high,low,close,volume,source_file,source_month
0,2015-01-02,AALI,16715.333882,17196.845842,16680.940171,16904.500000,1385945.0,NaN,NaN
1,2015-01-05,AALI,16921.693891,16990.481305,16749.725357,16973.285156,619089.0,NaN,NaN
2,2015-01-06,AALI,16904.506029,16904.506029,16629.356240,16715.339844,1142676.0,NaN,NaN
3,2015-01-07,AALI,16715.332749,16990.482422,16715.332749,16990.482422,1882560.0,NaN,NaN
4,2015-01-08,AALI,17093.667511,17454.802245,17093.667511,17351.621094,1504852.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2001168,2026-03-06,ZATA,0.000000,133.000000,133.000000,133.000000,1219300.0,all_2026_ohlcv.csv,ohlcv
2001169,2026-03-06,ZBRA,0.000000,0.000000,0.000000,50.000000,0.0,all_2026_ohlcv.csv,ohlcv
2001170,2026-03-06,ZINC,0.000000,35.000000,34.000000,35.000000,8051600.0,all_2026_ohlcv.csv,ohlcv
2001171,2026-03-06,ZONE,0.000000,476.000000,440.000000,466.000000,5900.0,all_2026_ohlcv.csv,ohlcv
2001172,2026-03-06,ZYRX,149.000000,149.000000,146.000000,148.000000,200800.0,all_2026_ohlcv.csv,ohlcv