# Get data IHSG from Yahoo Finance

In [1]:
import yfinance as yf
import pandas as pd
from datetime import datetime

from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

# IHSG/JKSE Range `2015 ~ 2026`

In [3]:
ihsg = yf.download(
    tickers="^JKSE",
    start="2026-01-01",
    end=datetime.today().strftime("%Y-%m-%d"),
    interval="1d"
)

ihsg.columns = ihsg.columns.droplevel(1)

cols = ["Open", "High", "Low", "Close", "Volume"]

ihsg[cols] = ihsg[cols].round(2)

ihsg = ihsg.reset_index()

ihsg["Ticker"] = "IHSG"

ihsg.columns = ihsg.columns.str.lower()

display(ihsg.head())


ihsg = ihsg[['date','ticker','open','high','low','close','volume']]

# ihsg.to_csv("/Users/albert/Documents/Finances/projects/venv/data/ihsg.csv", index=False)

ihsg

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yfinance/scrapers/history.py:201: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  dt_now = pd.Timestamp.utcnow()
[*********************100%***********************]  1 of 1 completed

Price       date    close     high      low     open     volume ticker
0     2026-01-02  8748.13  8748.13  8664.97  8676.74  471863900   IHSG
1     2026-01-05  8859.19  8859.19  8732.32  8778.73  665735100   IHSG
2     2026-01-06  8933.61  8940.11  8839.01  8890.72  630432800   IHSG
3     2026-01-07  8944.81  8970.87  8916.03  8959.09  655409500   IHSG
4     2026-01-08  8925.47  9002.92  8918.41  8946.70  489316100   IHSG

Price       date ticker     open     high      low    close     volume
0     2026-01-02   IHSG  8676.74  8748.13  8664.97  8748.13  471863900
1     2026-01-05   IHSG  8778.73  8859.19  8732.32  8859.19  665735100
2     2026-01-06   IHSG  8890.72  8940.11  8839.01  8933.61  630432800
3     2026-01-07   IHSG  8959.09  8970.87  8916.03  8944.81  655409500
4     2026-01-08   IHSG  8946.70  9002.92  8918.41  8925.47  489316100
..           ...    ...      ...      ...      ...      ...        ...
76    2026-05-04   IHSG  6988.92  7069.69  6946.06  6971.95  553310400
77    2026-05-05   IHSG  6968.57  7069.21  6921.61  7057.11  364949700
78    2026-05-06   IHSG  7086.34  7127.72  7049.92  7092.47  338543400
79    2026-05-07   IHSG  7160.79  7207.08  7107.17  7174.32  327636900
80    2026-05-08   IHSG  7182.96  7186.83  6969.40  6969.40  393674100

[81 rows x 7 columns]

# OHLCV Currency `USD/IDR`

In [3]:
usd_idr = yf.download(
    tickers="IDR=X",
    start="2015-01-01",
    end=datetime.today().strftime("%Y-%m-%d"),
    interval="1d"
)

# forex biasanya tidak punya level kolom kedua seperti saham indeks
if isinstance(usd_idr.columns, pd.MultiIndex):
    usd_idr.columns = usd_idr.columns.droplevel(1)

cols = ["Open", "High", "Low", "Close"]

usd_idr[cols] = usd_idr[cols].round(2)

usd_idr = usd_idr.reset_index()
usd_idr["Ticker"] = "USDIDR"

usd_idr.columns = usd_idr.columns.str.lower()

[*********************100%***********************]  1 of 1 completed

# BRENT OIL

In [4]:
brent = yf.download(
    tickers="BZ=F",
    start="2015-01-01",
    end=datetime.today().strftime("%Y-%m-%d"),
    interval="1d"
)

# Jika data memiliki MultiIndex, drop level kedua
if isinstance(brent.columns, pd.MultiIndex):
    brent.columns = brent.columns.droplevel(1)

cols = ["Open", "High", "Low", "Close"]

# Bulatkan harga 2 desimal
brent[cols] = brent[cols].round(2)

# Reset index supaya tanggal jadi kolom
brent = brent.reset_index()
brent["Ticker"] = "BRENT"

# Semua kolom menjadi huruf kecil
brent.columns = brent.columns.str.lower()

brent.head()

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BZ=F']: TypeError("'NoneType' object is not subscriptable")

Empty DataFrame
Columns: [date, adj close, close, high, low, open, volume, ticker]
Index: []

# COAL

In [22]:
coal = yf.download(
    tickers="QCL=F",
    start="2015-01-01",
    end=datetime.today().strftime("%Y-%m-%d"),
    interval="1d"
)

# Handle MultiIndex jika ada
if isinstance(coal.columns, pd.MultiIndex):
    coal.columns = coal.columns.droplevel(1)

cols = ["Open", "High", "Low", "Close"]

coal[cols] = coal[cols].round(2)
coal = coal.reset_index()
coal["Ticker"] = "COAL"

coal.columns = coal.columns.str.lower()

coal.head()

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: QCL=F"}}}
$QCL=F: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['QCL=F']: possibly delisted; no timezone found

Empty DataFrame
Columns: [date, adj close, close, high, low, open, volume, ticker]
Index: []

In [24]:
coal_etf = yf.download("KOL", start="2015-01-01", end=datetime.today().strftime("%Y-%m-%d"))
print(coal_etf.head())

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open Volume
Ticker             KOL         KOL         KOL         KOL    KOL
Date
2015-01-02  145.800003  146.600006  144.899994  146.600006   2795
2015-01-05  143.500000  145.800003  142.399994  145.800003   9054
2015-01-06  141.800003  144.100006  140.399994  143.199997   7148
2015-01-07  142.899994  143.600006  141.899994  143.600006  14077
2015-01-08  143.699997  143.934006  142.800003  142.899994   2821

# SAVINGS THE DATA FROM YF

In [5]:
usd_idr = usd_idr[['date','ticker','open','high','low','close']]
# brent = brent[['date', 'close', 'high', 'low', 'open', 'volume', 'ticker']]

usd_idr.to_csv("/Users/albert/Documents/Finances/projects/venv/data/macro/usdidr.csv", index=False)
# brent.to_csv("/Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/rolling_master/currency/brent_oils_2015-2026_ohlcv.csv", index=False)

display(usd_idr)
# display(brent)

Price       date  ticker     open     high       low    close
0     2015-01-01  USDIDR  12390.0  12390.0  12390.00  12390.0
1     2015-01-02  USDIDR  12435.0  12550.0  12397.00  12390.0
2     2015-01-05  USDIDR  12535.0  12685.0  12430.00  12480.0
3     2015-01-06  USDIDR  12630.0  12675.0  12580.00  12625.0
4     2015-01-07  USDIDR  12695.0  12755.0  12415.00  12635.0
...          ...     ...      ...      ...       ...      ...
2905  2026-03-03  USDIDR  16863.0  17005.0  16848.00  16863.0
2906  2026-03-04  USDIDR  16898.1  16951.0  16837.00  16898.1
2907  2026-03-05  USDIDR  16865.0  16951.0  16829.20  16865.0
2908  2026-03-06  USDIDR  16913.1  16994.0  16801.57  16913.1
2909  2026-03-07  USDIDR  16900.0  16900.0  16900.00  16900.0

[2910 rows x 6 columns]

# Concat data last year for specific Ticker

## Concat all dataset from 2025

In [8]:
import pandas as pd
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

In [18]:
base_dir = Path("/Users/albert/Documents/Finances/data/raw/market_data/idx_summaries")

def read_file(file):
    try:
        df = pd.read_excel(file)
        df["source_file"] = file.name
        return df
    except Exception as e:
        print(f"Error reading {file}: {e}")
        return None

In [19]:
files = list(base_dir.rglob("*.xlsx"))

with ThreadPoolExecutor(max_workers=8) as executor:
    dfs = list(executor.map(read_file, files))

# Filter None if failed load the data
dfs = [d for d in dfs if d is not None]

# Concat all dataset into a DataFrame 
final_df = pd.concat(dfs, ignore_index=True)

final_df.columns = final_df.columns.str.lower().str.strip().str.replace(" ", "_")

In [20]:
# Transform date
final_df["date"] = pd.to_datetime(final_df["date"], errors='coerce')
final_df = final_df.rename(columns={"stockcode": "ticker", "openprice": "open"})

In [21]:
# filter cols
cols_to_keep = ['date', 'ticker', 'open', 'high', 'low', 'close', 'volume']
stock_summary = final_df[cols_to_keep].copy()

In [22]:
# Remove Duplicaate & Sort
stock_summary = stock_summary.drop_duplicates(subset=['date', 'ticker'], keep='last')
stock_summary = stock_summary.sort_values(by=["date", "ticker"]).reset_index(drop=True)

In [ ]:
stock_summary_bumi = stock_summary[stock_summary['ticker'] == 'BUMI']
stock_summary_bumi.to_csv(
    "/Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ticker_daily_ohlcv/bumi_2025-2026_ohlcv.csv",
    index=False
)

In [ ]:
# from concurrent.futures import ThreadPoolExecutor

# def read_file(file):
#     df = pd.read_excel(file)
#     df["source_file"] = file.name
#     df["source_month"] = file.parent.name
#     return df

# files = list(root_dir.rglob("*.xlsx"))

# with ThreadPoolExecutor(max_workers=8) as executor:
#     dfs = list(executor.map(read_file, files))

# final_df = pd.concat(dfs, ignore_index=True)

# final_df.columns = (
#     final_df.columns
#         .str.lower()
#         .str.strip()
#         .str.replace(" ", "_")
# )
# final_df["date"] = pd.to_datetime(final_df["date"])
# final_df = final_df.sort_values(
#     by=["date", "stockcode"]
# ).reset_index(drop=True)

# final_df.head()


# stock_summary = final_df[['date', 'stockcode', 'openprice', 'high', 'low', 'close', 'volume']]

# stock_summary = stock_summary.rename(columns={
#     "stockcode": "ticker",
#     "openprice": "open"
# })


# stock_summary.head()

# Getting OHLCV for a specific ticker

## OHLCV BUMI

In [17]:
# stock_summary_bumi = stock_summary[stock_summary['ticker'] == 'BUMI']
# stock_summary_bumi = stock_summary_bumi.reset_index(drop=True)

# stock_summary_bumi.to_csv(
#     "/Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/CAMS/bumi_2025-2026_ohlcv.csv",
#     index=False
#     )

# stock_summary_bumi_2026 = stock_summary[stock_summary['ticker'] == 'BUMI']
# stock_summary_bumi_2026 = stock_summary_bumi_2026.reset_index(drop=True)


# stock_summary_bumi = pd.concat(
#     [stock_summary_bumi, stock_summary_bumi_2026],
#     ignore_index=True
#     )

# stock_summary_bumi.to_csv(
#     "/Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/CAMS/bumi_2025-2026_ohlcv.csv", 
#     index=False
#     )

# stock_summary_bumi


# bum = pd.read_csv("/Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/CAMS/bumi_2025-2026_ohlcv.csv")

# bum = bum.sort_values('date').drop_duplicates(subset=['date'], keep='last')

# bum.to_csv(
#     "/Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/CAMS/bumi_2025-2026_ohlcv.csv",
#     index=False
#     )

# bum['date'].duplicated().sum()

         date ticker  open  high  low  close       volume
0  2026-01-02   BUMI   372   424  370    420  11771094600
1  2026-01-05   BUMI   428   476  420    464  13048421800
2  2026-01-06   BUMI   466   484  452    464   8648116700
3  2026-01-07   BUMI   464   478  452    452   6102514400
4  2026-01-08   BUMI   450   460  442    460   3629921000
5  2026-01-09   BUMI   470   480  456    462   7430491000
6  2026-01-12   BUMI   468   472  394    436   9759299800
7  2026-01-13   BUMI   436   448  396    406   9716507600
8  2026-01-14   BUMI   414   434  410    422   6113687100
9  2026-01-15   BUMI   426   428  404    410   4173617100
10 2026-01-19   BUMI   410   412  390    412   6004590000
11 2026-01-20   BUMI   432   440  414    414   9992920600
12 2026-01-21   BUMI   408   408  380    386   8369517000
13 2026-01-22   BUMI   390   396  346    348  11300872300
14 2026-01-23   BUMI   350   364  330    360   9715093500

In [ ]:
# data_ohlcv = "/Users/albert/Documents/Finances/data/raw/ohlcv"

# !tree -f -L 5 {data_ohlcv}

/Users/albert/Documents/Finances/data/raw/ohlcv
├── /Users/albert/Documents/Finances/data/raw/ohlcv/event_data
│   ├── /Users/albert/Documents/Finances/data/raw/ohlcv/event_data/BUMI_20250110_20260124.json
│   └── /Users/albert/Documents/Finances/data/raw/ohlcv/event_data/bumi_news_20251008_20251125.json
└── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data
    ├── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/BUMI_20250110-20260123_ohlcv.csv
    ├── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ihsg_2025-2026_ohlcv.csv
    ├── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ihsg_20250110-20260123_ohlcv.csv
    └── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ticker_daily_ohlcv
        ├── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ticker_daily_ohlcv/BUMI_20251001_20251128_ohlcv.csv
        ├── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ticker_daily_ohlcv/BUMI_daily_ohlcv.csv
        └── /Users/albert/Documents/Finances/data/raw/ohlcv/ticker_data/ticker_daily_ohlcv/IHSG_20241001_20251128_ohlcv.csv

4 directories, 8 files

In [7]:
final_df = download_idx_ohlcv(
    tickers=tickers,
    start="2015-01-01",
    interval="1d",
    batch_size=30
)

final_df.head()

  9%|▉         | 3/32 [00:07<01:07,  2.32s/it]
1 Failed download:
['BPII.JK']: TypeError("'NoneType' object is not subscriptable")
 53%|█████▎    | 17/32 [00:48<00:33,  2.21s/it]$MORA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")

1 Failed download:
['MORA.JK']: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
 66%|██████▌   | 21/32 [00:56<00:22,  2.07s/it]$IKAN.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BBSS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$INDO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TRIN.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$RONY.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$CBMF.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$AMAR.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PURA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$AMOR.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SOFA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$CSRA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TAMA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PTPW.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BHAT.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SAMF.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SBAT.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$DMND.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$KBAG.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$CASH.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TECH.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PGUN.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$EPAC.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$CSMI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PGJO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$UANG.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")

25 Failed downloads:
['IKAN.JK', 'BBSS.JK', 'INDO.JK', 'TRIN.JK', 'RONY.JK', 'CBMF.JK', 'AMAR.JK', 'PURA.JK', 'AMOR.JK', 'SOFA.JK', 'CSRA.JK', 'TAMA.JK', 'PTPW.JK', 'BHAT.JK', 'SAMF.JK', 'SBAT.JK', 'DMND.JK', 'KBAG.JK', 'CASH.JK', 'TECH.JK', 'PGUN.JK', 'EPAC.JK', 'CSMI.JK', 'PGJO.JK', 'UANG.JK']: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
 69%|██████▉   | 22/32 [01:02<00:31,  3.17s/it]$FIMP.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ZYRX.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SCNP.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BEBS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$LFLO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PNGO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$LUCY.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ATAP.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$HOMI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PLAN.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$WMUU.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TRJA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SGER.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PURI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$KMDS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$UNIQ.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SNLK.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SOHO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BANK.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BBSI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TOYS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PTDU.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$VICI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$EDGE.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ROCK.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PPGL.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$PMMP.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$NPGF.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ENZO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TAPG.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")

30 Failed downloads:
['FIMP.JK', 'ZYRX.JK', 'SCNP.JK', 'BEBS.JK', 'LFLO.JK', 'PNGO.JK', 'LUCY.JK', 'ATAP.JK', 'HOMI.JK', 'PLAN.JK', 'WMUU.JK', 'TRJA.JK', 'SGER.JK', 'PURI.JK', 'KMDS.JK', 'UNIQ.JK', 'SNLK.JK', 'SOHO.JK', 'BANK.JK', 'BBSI.JK', 'TOYS.JK', 'PTDU.JK', 'VICI.JK', 'EDGE.JK', 'ROCK.JK', 'PPGL.JK', 'PMMP.JK', 'NPGF.JK', 'ENZO.JK', 'TAPG.JK']: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
 72%|███████▏  | 23/32 [01:05<00:27,  3.06s/it]$WGSH.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$UVCR.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$HAIS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$LABA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BOBA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$IDEA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$CMRY.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BUKA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$IPAC.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$RSGK.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$MTEL.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$MASB.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$CMNT.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$HOPE.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ARCI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$FLMC.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$GTSI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$NICL.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$GPSO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$MCOL.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$KUAS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BMHS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$OILS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$DEPO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BINO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SBMA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$RUNS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TRUE.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$MGLV.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ADCP.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")

30 Failed downloads:
['WGSH.JK', 'UVCR.JK', 'HAIS.JK', 'LABA.JK', 'BOBA.JK', 'IDEA.JK', 'CMRY.JK', 'BUKA.JK', 'IPAC.JK', 'RSGK.JK', 'MTEL.JK', 'MASB.JK', 'CMNT.JK', 'HOPE.JK', 'ARCI.JK', 'FLMC.JK', 'GTSI.JK', 'NICL.JK', 'GPSO.JK', 'MCOL.JK', 'KUAS.JK', 'BMHS.JK', 'OILS.JK', 'DEPO.JK', 'BINO.JK', 'SBMA.JK', 'RUNS.JK', 'TRUE.JK', 'MGLV.JK', 'ADCP.JK']: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
 75%|███████▌  | 24/32 [01:08<00:23,  2.98s/it]$GOTO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ASLC.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BAUT.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$OLIV.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$AVIA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$NTBK.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$WINR.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$DRMA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TLDN.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$NANO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ASHA.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$ADMR.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$IPPE.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$TAYS.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SICO.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$WMPP.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SMKM.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$NASI.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$MTMH.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$OBMD.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$BIKE.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")
$SWID.JK: possibly delisted; no price data found  (1d 2015-01-01 -> 2019-12-31) (Yahoo error = "Data doesn't exist for startDate = 1420045200, endDate = 1577725200")

Price,date,ticker,open,high,low,close,volume
0,2015-01-02,AALI,16715.333882,17196.845842,16680.940171,16904.500000,1385945.0
1,2015-01-05,AALI,16921.693891,16990.481305,16749.725357,16973.285156,619089.0
2,2015-01-06,AALI,16904.506029,16904.506029,16629.356240,16715.339844,1142676.0
3,2015-01-07,AALI,16715.332749,16990.482422,16715.332749,16990.482422,1882560.0
4,2015-01-08,AALI,17093.667511,17454.802245,17093.667511,17351.621094,1504852.0

In [8]:
final_df

Price,date,ticker,open,high,low,close,volume
0,2015-01-02,AALI,16715.333882,17196.845842,16680.940171,16904.500000,1385945.0
1,2015-01-05,AALI,16921.693891,16990.481305,16749.725357,16973.285156,619089.0
2,2015-01-06,AALI,16904.506029,16904.506029,16629.356240,16715.339844,1142676.0
3,2015-01-07,AALI,16715.332749,16990.482422,16715.332749,16990.482422,1882560.0
4,2015-01-08,AALI,17093.667511,17454.802245,17093.667511,17351.621094,1504852.0
...,...,...,...,...,...,...,...
720639,2019-12-20,WIFI,NaN,NaN,NaN,NaN,NaN
720640,2019-12-23,WIFI,NaN,NaN,NaN,NaN,NaN
720641,2019-12-26,WIFI,NaN,NaN,NaN,NaN,NaN
720642,2019-12-27,WIFI,NaN,NaN,NaN,NaN,NaN
720643,2019-12-30,WIFI,NaN,NaN,NaN,NaN,NaN

In [9]:
final_df.to_csv("/Users/albert/Documents/Finances/data/processed/market/ohlcv_all_stocks_2015-2019.csv", index=False)